name: 'PyPruningRadixTrie release pipeline'
on:
  workflow_dispatch:
concurrency: ${{ github.ref }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Tests
        run: python -m unittest

  release-pypi:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@master
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
      
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

